version: '3'
services:
    db_mongo:
        image: mongo
        container_name: db_mongo
        volumes:
            - mongodata:/data/db
        ports:
            - '27017:27017'
    core:
        depends_on:
            - db_mongo
        restart: always
        container_name: core
        build: .
        ports:
            - '3000:3000'
        environment:
            - DATABASE_HOST=db_mongo
            - DATABASE_STRING=mongodb://db_mongo:27017
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules

volumes:
    mongodata:
