version: '3'
services:
  back_app:
    depends_on:
      - db
    restart: always
    build: .
    ports:
      - '3000:3000'
    environment:
      - DATABASE_HOST=db_mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: mongo
    container_name: db_mongo
    volumes:
      - mongodata:/data/db
    ports:
      - '27017:27017'

volumes:
  mongodata:
